"""
Generate a NON-DESTRUCTIVE baseline migration from database.types.ts Row shapes.

Purpose: version tables that exist in production types but not in repo migrations.
Does NOT invent RPC bodies — writes a companion RPC inventory SQL with comments only.

ponytail: approximate column types from TS (string→text, number→numeric, boolean→boolean, Json→jsonb).
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TYPES_PATH = ROOT / "src/lib/supabase/database.types.ts"
OUT_DIR = ROOT / "supabase/migrations"
REPORT = ROOT / "supabase" / "SCHEMA_BASELINE_REPORT.md"

TS = TYPES_PATH.read_text(encoding="utf-8", errors="replace")


def ts_to_sql(ts_type: str) -> str:
    t = ts_type.strip()
    if t.startswith("Json"):
        return "jsonb"
    if "boolean" in t:
        return "boolean"
    if "number" in t:
        return "numeric"
    if "string" in t:
        return "text"
    if t.endswith("[]") or "Array<" in t:
        return "jsonb"
    return "text"


def parse_tables() -> dict[str, list[tuple[str, str, bool]]]:
    """table -> list of (col, sql_type, nullable)"""
    tables: dict[str, list[tuple[str, str, bool]]] = {}
    # match: name: { Row: { ... } Insert:
    for m in re.finditer(
        r"^\s{6}([a-z_][a-z0-9_]*):\s*\{\s*\n\s{8}Row:\s*\{([\s\S]*?)\n\s{8}\}",
        TS,
        re.M,
    ):
        name = m.group(1)
        row = m.group(2)
        cols: list[tuple[str, str, bool]] = []
        for cm in re.finditer(r"^\s{10}([a-z_][a-z0-9_]*)\??:\s*(.+)$", row, re.M):
            col = cm.group(1)
            raw = cm.group(2).strip()
            nullable = "| null" in raw or raw.endswith("| null")
            base = raw.replace("| null", "").replace(";", "").strip()
            cols.append((col, ts_to_sql(base), nullable))
        if cols:
            tables[name] = cols
    return tables


def parse_functions() -> list[str]:
    funcs = sorted(set(re.findall(r"^\s{6}([a-z_][a-z0-9_]*):\s*\{\s*\n\s{8}Args:", TS, re.M)))
    return funcs


def mig_existing() -> tuple[set[str], set[str]]:
    text = "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in OUT_DIR.glob("*.sql"))
    tables = set(re.findall(r"CREATE TABLE(?: IF NOT EXISTS)?\s+(?:public\.)?([a-z_][a-z0-9_]*)", text, re.I))
    funcs = set(
        re.findall(r"CREATE(?: OR REPLACE)? FUNCTION\s+(?:public\.)?([a-z_][a-z0-9_]*)", text, re.I)
    )
    return tables, funcs


def main() -> None:
    tables = parse_tables()
    funcs = parse_functions()
    mig_tables, mig_funcs = mig_existing()
    missing_tables = sorted(t for t in tables if t not in mig_tables)
    missing_funcs = sorted(f for f in funcs if f not in mig_funcs)

    today = date.today().strftime("%Y%m%d")
    baseline_path = OUT_DIR / f"{today}_schema_baseline_tables_from_types.sql"
    rpc_path = OUT_DIR / f"{today}_schema_baseline_rpc_inventory.sql"

    lines = [
        "-- AUTO-GENERATED from src/lib/supabase/database.types.ts",
        "-- Purpose: version production tables missing from repo migrations.",
        "-- Safe: CREATE TABLE IF NOT EXISTS only. No DROP. No data.",
        "-- Column types are approximate (TS→SQL). Refine after live dump.",
        "-- Generated by scripts/generate_schema_baseline_from_types.py",
        "",
        "BEGIN;",
        "",
    ]
    for t in missing_tables:
        cols = tables[t]
        lines.append(f"-- Table: public.{t}")
        lines.append(f"CREATE TABLE IF NOT EXISTS public.{t} (")
        col_sql = []
        pk = "id" if any(c[0] == "id" for c in cols) else None
        for col, sql_t, nullable in cols:
            null_sql = "" if not nullable and col == pk else ("" if not nullable else "")
            # keep simple: all columns nullable except id if present
            if col == "id":
                col_sql.append(f"  {col} text PRIMARY KEY")
            else:
                col_sql.append(f"  {col} {sql_t}")
        lines.append(",\n".join(col_sql))
        lines.append(");")
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    baseline_path.write_text("\n".join(lines), encoding="utf-8")

    rpc_lines = [
        "-- RPC INVENTORY (not executable stubs)",
        "-- Functions present in database.types.ts or called from src but not fully versioned here.",
        "-- Do NOT invent business logic. Next step: `supabase db dump --schema public` with service role.",
        "",
    ]
    for f in missing_funcs:
        rpc_lines.append(f"-- TODO version RPC: public.{f}")
    # also list src-only RPCs
    src_text = ""
    for p in (ROOT / "src").rglob("*"):
        if p.suffix in {".ts", ".tsx"}:
            src_text += p.read_text(encoding="utf-8", errors="replace")
    rpc_used = sorted(set(re.findall(r"\.rpc\(\s*['\"]([a-z_][a-z0-9_]*)['\"]", src_text)))
    rpc_lines.append("")
    rpc_lines.append("-- RPCs referenced from application code:")
    for r in rpc_used:
        status = "VERSIONED_IN_MIG" if r in mig_funcs else "NEEDS_VERSIONING"
        rpc_lines.append(f"--   {r}  [{status}]")
    rpc_lines.append("")
    rpc_path.write_text("\n".join(rpc_lines), encoding="utf-8")

    report = f"""# Schema Baseline Report

**Generated:** {date.today().isoformat()}  
**Source of truth (types):** `src/lib/supabase/database.types.ts`  
**Migrations before:** {len(mig_tables)} tables, {len(mig_funcs)} functions  
**Types:** {len(tables)} tables, {len(funcs)} functions  

## Gap

| Kind | In types | In migrations | Missing from migrations |
|------|----------|---------------|-------------------------|
| Tables | {len(tables)} | {len(mig_tables)} | {len(missing_tables)} |
| Functions | {len(funcs)} | {len(mig_funcs)} | {len(missing_funcs)} |

## Artifacts

- `{baseline_path.name}` — `CREATE TABLE IF NOT EXISTS` for {len(missing_tables)} missing tables
- `{rpc_path.name}` — inventory of RPCs still needing real SQL bodies

## Missing tables

{chr(10).join(f"- `{t}`" for t in missing_tables) or "- (none)"}

## Missing / unversioned functions (types)

{chr(10).join(f"- `{f}`" for f in missing_funcs) or "- (none)"}

## App RPC calls needing versioning

{chr(10).join(f"- `{r}`" for r in rpc_used if r not in mig_funcs) or "- (none)"}

## How to replace with live dump (when service role available)

```bash
# Load Skillset env (NOT Lugano keys from the vault file)
# Required: NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in project .env.local
npx supabase db dump --schema public -f supabase/migrations/{today}_live_schema_dump.sql
```

**Note:** Vault `Todas as APIs Oficial.env` currently exposes **Lugano** Supabase keys (`LUGANO_SUPABASE_*`), not Skillset. Use Skillset project keys only.

## Safety

- Baseline uses `IF NOT EXISTS` only.
- Column types are TS approximations (text/numeric/boolean/jsonb).
- No RLS policies generated here — add after live dump.
- No secrets in this report.
"""
    REPORT.write_text(report, encoding="utf-8")
    print(f"Wrote {baseline_path}")
    print(f"Wrote {rpc_path}")
    print(f"Wrote {REPORT}")
    print(f"missing_tables={len(missing_tables)} missing_funcs={len(missing_funcs)}")


if __name__ == "__main__":
    main()
