-- AUTO-GENERATED from src/lib/supabase/database.types.ts
-- Purpose: version production tables missing from repo migrations.
-- Safe: CREATE TABLE IF NOT EXISTS only. No DROP. No data.
-- Column types are approximate (TS→SQL). Refine after live dump.
-- Generated by scripts/generate_schema_baseline_from_types.py

BEGIN;

-- Table: public.account_action_requests
CREATE TABLE IF NOT EXISTS public.account_action_requests (
  email text,
  id text PRIMARY KEY,
  requested_at text,
  requested_by text,
  resolved_at text,
  resolved_by text,
  status text,
  type text,
  updated_at text
);

-- Table: public.audit_log
CREATE TABLE IF NOT EXISTS public.audit_log (
  action text,
  actor_email text,
  actor_id text,
  created_at text,
  id text PRIMARY KEY,
  metadata jsonb,
  summary text,
  target_id text,
  target_type text
);

-- Table: public.certificates
CREATE TABLE IF NOT EXISTS public.certificates (
  authority_label text,
  course_category text,
  course_id text,
  course_slug text,
  course_title text,
  created_at text,
  enrollment_id text,
  id text PRIMARY KEY,
  issued_at text,
  sponsor_logo_url text,
  status text,
  student_full_name text,
  teacher_name text,
  teacher_signature_url text,
  updated_at text,
  user_id text,
  verification_code text
);

-- Table: public.checkout_locks
CREATE TABLE IF NOT EXISTS public.checkout_locks (
  acquired_at text,
  checkout_session_id text,
  checkout_url text,
  course_id text,
  expires_at text,
  lock_key text,
  order_id text,
  updated_at text,
  user_id text
);

-- Table: public.community_comments
CREATE TABLE IF NOT EXISTS public.community_comments (
  author_id text,
  author_name text,
  author_role text,
  body text,
  course_slug text,
  created_at text,
  id text PRIMARY KEY,
  parent_id text,
  post_id text,
  updated_at text
);

-- Table: public.community_post_likes
CREATE TABLE IF NOT EXISTS public.community_post_likes (
  created_at text,
  liker_id text,
  post_id text
);

-- Table: public.community_posts
CREATE TABLE IF NOT EXISTS public.community_posts (
  author_id text,
  author_name text,
  author_role text,
  body text,
  category text,
  course_slug text,
  created_at text,
  id text PRIMARY KEY,
  pinned boolean,
  updated_at text
);

-- Table: public.community_reports
CREATE TABLE IF NOT EXISTS public.community_reports (
  comment_id text,
  course_slug text,
  created_at text,
  detail text,
  id text PRIMARY KEY,
  post_id text,
  reason text,
  reporter_email text,
  reporter_id text,
  reporter_name text,
  status text,
  target_author_id text,
  target_author_name text,
  target_type text,
  updated_at text
);

-- Table: public.course_assets
CREATE TABLE IF NOT EXISTS public.course_assets (
  bunny_video_id text,
  content_type text,
  course_id text,
  created_at text,
  download_url text,
  file_name text,
  id text PRIMARY KEY,
  is_preview boolean,
  kind text,
  lesson_id text,
  module_id text,
  owner_id text,
  size numeric,
  storage_path text,
  updated_at text
);

-- Table: public.course_event_rsvps
CREATE TABLE IF NOT EXISTS public.course_event_rsvps (
  attendee_email text,
  attendee_name text,
  course_slug text,
  created_at text,
  event_id text,
  status text,
  uid text,
  updated_at text,
  user_id text
);

-- Table: public.course_events
CREATE TABLE IF NOT EXISTS public.course_events (
  course_id text,
  course_slug text,
  course_title text,
  created_at text,
  description text,
  external_url text,
  id text PRIMARY KEY,
  owner_id text,
  recording_asset_id text,
  starts_at text,
  status text,
  title text,
  type text,
  updated_at text
);

-- Table: public.course_lesson_content
CREATE TABLE IF NOT EXISTS public.course_lesson_content (
  content_text text,
  course_id text,
  created_at text,
  external_url text,
  lesson_id text,
  updated_at text
);

-- Table: public.course_messages
CREATE TABLE IF NOT EXISTS public.course_messages (
  body text,
  course_id text,
  course_title text,
  created_at text,
  id text PRIMARY KEY,
  sender_id text,
  student_id text,
  student_name text,
  teacher_id text
);

-- Table: public.course_reviews
CREATE TABLE IF NOT EXISTS public.course_reviews (
  author_name text,
  body text,
  course_id text,
  created_at text,
  id text PRIMARY KEY,
  rating numeric,
  status text,
  updated_at text
);

-- Table: public.course_subscriptions
CREATE TABLE IF NOT EXISTS public.course_subscriptions (
  cancel_at_period_end boolean,
  course_id text,
  course_slug text,
  created_at text,
  current_period_end text,
  id text PRIMARY KEY,
  interval text,
  latest_invoice_id text,
  past_due boolean,
  status text,
  stripe_customer_id text,
  stripe_subscription_id text,
  teacher_id text,
  updated_at text,
  user_id text
);

-- Table: public.course_title_keys
CREATE TABLE IF NOT EXISTS public.course_title_keys (
  title_key text
);

-- Table: public.courses
CREATE TABLE IF NOT EXISTS public.courses (
  categories text,
  category text,
  community_enabled boolean,
  cover_image_url text,
  created_at text,
  currency text,
  drip_interval_days numeric,
  drip_strategy text,
  enrollment_count numeric,
  featured boolean,
  featured_rank numeric,
  free_preview_lesson_id text,
  id text PRIMARY KEY,
  installments_enabled boolean,
  installments_max numeric,
  learning_outcomes text,
  lesson_count numeric,
  members_cover_asset_id text,
  members_description text,
  members_subtitle text,
  members_theme text,
  members_title text,
  modules jsonb,
  owner_id text,
  payment_type text,
  platform_fee_bps numeric,
  price_amount_minor numeric,
  rating_average numeric,
  rating_count numeric,
  rating_sum numeric,
  review_count numeric,
  review_note text,
  slug text,
  status text,
  stripe_connected_account_id text,
  stripe_subscription_price jsonb,
  summary text,
  title text,
  title_key text,
  trending_score numeric,
  updated_at text
);

-- Table: public.enrollments
CREATE TABLE IF NOT EXISTS public.enrollments (
  course_category text,
  course_id text,
  course_image text,
  course_slug text,
  course_title text,
  created_at text,
  id text PRIMARY KEY,
  last_lesson_id text,
  progress_percent numeric,
  source text,
  status text,
  subscription_id text,
  updated_at text,
  user_id text
);

-- Table: public.leaderboards
CREATE TABLE IF NOT EXISTS public.leaderboards (
  entries jsonb,
  updated_at text,
  window text
);

-- Table: public.learning_path_items
CREATE TABLE IF NOT EXISTS public.learning_path_items (
  course_id text,
  id text PRIMARY KEY,
  path_id text,
  position numeric
);

-- Table: public.learning_paths
CREATE TABLE IF NOT EXISTS public.learning_paths (
  created_at text,
  description text,
  id text PRIMARY KEY,
  position numeric,
  status text,
  title text,
  updated_at text
);

-- Table: public.lesson_comments
CREATE TABLE IF NOT EXISTS public.lesson_comments (
  author_id text,
  author_name text,
  body text,
  course_id text,
  created_at text,
  id text PRIMARY KEY,
  lesson_id text,
  updated_at text
);

-- Table: public.lesson_progress
CREATE TABLE IF NOT EXISTS public.lesson_progress (
  completed_at text,
  enrollment_id text,
  lesson_id text,
  user_id text
);

-- Table: public.member_stats
CREATE TABLE IF NOT EXISTS public.member_stats (
  display_name text,
  level numeric,
  points numeric,
  total_likes_received numeric,
  uid text,
  updated_at text
);

-- Table: public.notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  actor_name text,
  body text,
  created_at text,
  link text,
  notification_id text,
  read boolean,
  title text,
  type text,
  user_id text
);

-- Table: public.orders
CREATE TABLE IF NOT EXISTS public.orders (
  amount_minor numeric,
  checkout_session_id text,
  course_id text,
  course_slug text,
  course_title text,
  created_at text,
  currency text,
  id text PRIMARY KEY,
  latest_transfer_reversal_at text,
  latest_transfer_reversal_id text,
  paid_at text,
  payment_intent_id text,
  payout_model text,
  platform_fee_bps numeric,
  provider text,
  receipt_url text,
  refund_request_id text,
  refund_requested_at text,
  refunded_amount_minor numeric,
  status text,
  teacher_id text,
  teacher_stripe_connected_account_id text,
  transfer_reversed_amount_minor numeric,
  updated_at text,
  user_id text
);

-- Table: public.payments
CREATE TABLE IF NOT EXISTS public.payments (
  amount_minor numeric,
  course_id text,
  created_at text,
  currency text,
  id text PRIMARY KEY,
  order_id text,
  provider text,
  provider_payment_id text,
  receipt_url text,
  refunded_amount_minor numeric,
  refunded_at text,
  status text,
  updated_at text,
  user_id text
);

-- Table: public.payout_ledger
CREATE TABLE IF NOT EXISTS public.payout_ledger (
  amount_minor numeric,
  course_id text,
  created_at text,
  currency text,
  gross_amount_minor numeric,
  id text PRIMARY KEY,
  invoice_id text,
  kind text,
  latest_transfer_reversal_at text,
  latest_transfer_reversal_id text,
  net_amount_minor numeric,
  order_id text,
  payment_id text,
  payment_id_is_payment_intent boolean,
  planned_transfer_amount_minor numeric,
  platform_fee_bps numeric,
  platform_fee_minor numeric,
  refund_reversal_claims jsonb,
  refunded_amount_minor numeric,
  refunded_at text,
  release_at text,
  skillset_fee_minor numeric,
  status text,
  stripe_fee_minor numeric,
  subscription_id text,
  teacher_id text,
  teacher_stripe_connected_account_id text,
  transfer_amount_minor numeric,
  transfer_id text,
  transfer_reversed_amount_minor numeric,
  updated_at text
);

-- Table: public.platform_config
CREATE TABLE IF NOT EXISTS public.platform_config (
  doc_id text,
  payout_release_delay_days numeric
);

-- Table: public.points_events
CREATE TABLE IF NOT EXISTS public.points_events (
  created_at text,
  delta numeric,
  id text PRIMARY KEY,
  kind text,
  liker_id text,
  post_id text,
  uid text
);

-- Table: public.processed_stripe_events
CREATE TABLE IF NOT EXISTS public.processed_stripe_events (
  claimed_at text,
  processed_at text,
  status text,
  stripe_event_id text
);

-- Table: public.public_profiles
CREATE TABLE IF NOT EXISTS public.public_profiles (
  bio text,
  credentials jsonb,
  display_name text,
  photo_url text,
  uid text,
  updated_at text,
  username text
);

-- Table: public.rate_limits
CREATE TABLE IF NOT EXISTS public.rate_limits (
  count numeric,
  key text,
  updated_at text,
  window_started_at text
);

-- Table: public.subscriptions
CREATE TABLE IF NOT EXISTS public.subscriptions (
  cancel_at_period_end boolean,
  created_at text,
  current_period_end text,
  current_period_start text,
  cycle text,
  id text PRIMARY KEY,
  past_due boolean,
  plan_id text,
  status text,
  stripe_customer_id text,
  stripe_price_id text,
  stripe_subscription_id text,
  updated_at text,
  user_id text
);

-- Table: public.support_tickets
CREATE TABLE IF NOT EXISTS public.support_tickets (
  admin_response text,
  category text,
  created_at text,
  id text PRIMARY KEY,
  message text,
  responded_at text,
  responded_by text,
  status text,
  subject text,
  updated_at text,
  user_email text,
  user_id text,
  user_name text
);

-- Table: public.users
CREATE TABLE IF NOT EXISTS public.users (
  bio text,
  created_at text,
  creator_verification_status text,
  credentials jsonb,
  current_plan_id text,
  display_name text,
  email text,
  goals jsonb,
  last_login_at text,
  marketing_consent boolean,
  onboarding_answers jsonb,
  onboarding_completed boolean,
  onboarding_completed_at text,
  onboarding_path text,
  phone_number text,
  photo_url text,
  preferences jsonb,
  privacy_accepted_at text,
  privacy_version text,
  roles jsonb,
  storefront jsonb,
  stripe_connect_charges_enabled boolean,
  stripe_connect_payouts_enabled boolean,
  stripe_connect_status text,
  stripe_connect_updated_at text,
  stripe_connected_account_id text,
  stripe_customer_id text,
  teacher_signature_url text,
  teacher_terms_accepted_at text,
  teacher_terms_version text,
  terms_accepted_at text,
  terms_version text,
  timezone text,
  uid text,
  updated_at text,
  username text
);

-- Table: public.wishlists
CREATE TABLE IF NOT EXISTS public.wishlists (
  course_id text,
  course_slug text,
  created_at text,
  id text PRIMARY KEY,
  updated_at text,
  user_id text
);

COMMIT;
