"use client";

import { Trash2, UploadCloud } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";

import { useAuth } from "@/components/auth/auth-provider";
import type {
  StorefrontConfig,
  StorefrontThemePreset,
} from "@/domain/user-profile";
import {
  isStorefrontHexColor,
  maxStorefrontTaglineLength,
  storefrontThemePresets,
} from "@/domain/user-profile";
import type { TeacherCourse } from "@/domain/teacher-course";
import {
  allowedAvatarTypes,
  isAllowedAvatarFile,
  removeUserStorefrontImage,
  storefrontImageRequirementLabel,
  uploadUserStorefrontImage,
  type StorefrontImageKind,
  type UploadAvatarProgress,
} from "@/lib/data/profile-media";
import { subscribeToTeacherCourses } from "@/lib/data/teacher-courses";
import { getUserProfile, updateUserStorefront } from "@/lib/data/user-profiles";
import { UploadProgressNote } from "@/components/teacher/upload-progress-note";

const themePresetLabels: Record<StorefrontThemePreset, string> = {
  default: "Platform default",
  warm: "Warm",
  cool: "Cool",
  mono: "Monochrome",
};

const defaultAccentColor = "#183a5e";

/**
 * Reorder a list by moving the item at `from` one slot in `direction`.
 * Returns a new array; out-of-range moves are no-ops.
 */
function moveItem<T>(items: T[], from: number, direction: -1 | 1): T[] {
  const to = from + direction;
  if (to < 0 || to >= items.length) {
    return items;
  }

  const next = [...items];
  const [moved] = next.splice(from, 1);
  next.splice(to, 0, moved);
  return next;
}

function StorefrontImageUpload({
  description,
  error,
  imageUrl,
  isUploading,
  kind,
  label,
  progress,
  onChange,
  onRemove,
}: {
  description: string;
  error: string;
  imageUrl: string;
  isUploading: boolean;
  kind: StorefrontImageKind;
  label: string;
  progress: UploadAvatarProgress | null;
  onChange: (file: File | null) => void;
  onRemove: () => void;
}) {
  const uploadLabel = `Upload storefront ${kind === "logo" ? "logo" : "hero image"}`;

  return (
    <div className="grid gap-3 border-t border-[var(--color-line)] pt-4 sm:grid-cols-[8rem_minmax(0,1fr)] sm:items-center">
      <div
        className={`relative grid overflow-hidden rounded-[8px] border border-[var(--color-line)] bg-white ${
          kind === "logo" ? "aspect-square w-24 place-items-center" : "aspect-[16/7] w-full"
        }`}
      >
        {imageUrl ? (
          // Storage URLs are generated by this app; plain img supports the
          // cache-busting query without adding a remote host to next/image.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={imageUrl}
            alt=""
            className={`h-full w-full ${kind === "logo" ? "object-contain p-2" : "object-cover"}`}
          />
        ) : (
          <UploadCloud
            aria-hidden="true"
            size={22}
            className="m-auto text-[var(--color-ink-muted)]"
          />
        )}
      </div>

      <div className="min-w-0">
        <p className="text-sm font-semibold text-[var(--color-ink)]">{label}</p>
        <p className="mt-1 text-xs leading-5 text-[var(--color-ink-soft)]">
          {description} {storefrontImageRequirementLabel}.
        </p>
        <div className="mt-3 flex flex-wrap items-center gap-2">
          <label
            className={`inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-[8px] border border-dashed border-[var(--color-line)] bg-white px-3 py-2 text-sm font-semibold text-[var(--color-primary)] transition-colors hover:border-[var(--color-primary-light)] ${
              isUploading ? "pointer-events-none opacity-60" : ""
            }`}
          >
            <UploadCloud aria-hidden="true" size={16} />
            {isUploading ? "Uploading..." : imageUrl ? "Replace" : "Upload"}
            <input
              type="file"
              accept={allowedAvatarTypes.join(",")}
              disabled={isUploading}
              aria-label={uploadLabel}
              onChange={(event) => {
                const file = event.target.files?.[0] ?? null;
                event.target.value = "";
                onChange(file);
              }}
              className="hidden"
            />
          </label>
          {imageUrl ? (
            <button
              type="button"
              onClick={onRemove}
              disabled={isUploading}
              aria-label={`Remove storefront ${kind === "logo" ? "logo" : "hero image"}`}
              title={`Remove ${label.toLowerCase()}`}
              className="inline-flex min-h-11 items-center gap-2 rounded-[8px] border border-[var(--color-line)] bg-white px-3 py-2 text-sm font-semibold text-[var(--color-ink-soft)] hover:text-[var(--color-ink)] disabled:opacity-60"
            >
              <Trash2 aria-hidden="true" size={15} />
              Remove
            </button>
          ) : null}
        </div>
        {progress ? (
          <div className="mt-2">
            <UploadProgressNote progress={progress} />
          </div>
        ) : null}
        {/* O erro nasce ao lado do botão que o disparou, e anunciado ao leitor
            de tela. No rodapé do formulário ficava fora da tela no celular, e o
            botão voltava a "Upload" como se nada tivesse acontecido. */}
        {error ? (
          <p
            role="alert"
            className="mt-2 rounded-[8px] border border-[rgba(178,34,52,0.2)] bg-[rgba(178,34,52,0.06)] px-3 py-2 text-xs font-semibold text-[var(--color-danger-fg)]"
          >
            {error}
          </p>
        ) : null}
      </div>
    </div>
  );
}

export function StorefrontSettingsPanel() {
  const { user } = useAuth();

  const [displayName, setDisplayName] = useState("");
  const [accentColor, setAccentColor] = useState("");
  const [logoUrl, setLogoUrl] = useState("");
  const [heroImageUrl, setHeroImageUrl] = useState("");
  const [themePreset, setThemePreset] = useState<StorefrontThemePreset>("default");
  const [tagline, setTagline] = useState("");
  const [orderedCourseIds, setOrderedCourseIds] = useState<string[]>([]);
  const [featuredCourseId, setFeaturedCourseId] = useState<string | null>(null);

  const [publishedCourses, setPublishedCourses] = useState<TeacherCourse[]>([]);

  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [uploadingImages, setUploadingImages] = useState<
    ReadonlySet<StorefrontImageKind>
  >(() => new Set());
  const [uploadProgress, setUploadProgress] = useState<
    Partial<Record<StorefrontImageKind, UploadAvatarProgress>>
  >({});
  const [pendingImageRemovals, setPendingImageRemovals] = useState<
    ReadonlySet<StorefrontImageKind>
  >(() => new Set());
  // Falha de imagem fica no campo dela; `error` é só para carregar/salvar.
  const [imageErrors, setImageErrors] = useState<
    Partial<Record<StorefrontImageKind, string>>
  >({});
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  function setImageError(kind: StorefrontImageKind, message: string) {
    setImageErrors((current) => ({ ...current, [kind]: message }));
  }

  // Load the saved storefront config.
  useEffect(() => {
    if (!user) {
      return;
    }

    let mounted = true;

    getUserProfile(user.uid)
      .then((profile) => {
        if (!mounted) {
          return;
        }

        const branding = profile?.storefront?.branding;
        const showcase = profile?.storefront?.showcase;

        setDisplayName(profile?.displayName ?? "");
        setAccentColor(branding?.accentColor ?? "");
        setLogoUrl(branding?.logoUrl ?? "");
        setHeroImageUrl(branding?.heroImageUrl ?? "");
        setThemePreset(branding?.themePreset ?? "default");
        setTagline(showcase?.tagline ?? "");
        setOrderedCourseIds(showcase?.orderedCourseIds ?? []);
        setFeaturedCourseId(showcase?.featuredCourseId ?? null);
      })
      .catch(() => {
        if (mounted) {
          setError("We could not load your storefront settings.");
        }
      })
      .finally(() => {
        if (mounted) {
          setIsLoading(false);
        }
      });

    return () => {
      mounted = false;
    };
  }, [user]);

  // Live list of this teacher's courses to drive the showcase ordering.
  useEffect(() => {
    if (!user) {
      return;
    }

    const unsubscribe = subscribeToTeacherCourses(
      user.uid,
      (courses) => {
        setPublishedCourses(
          courses.filter((course) => course.status === "published"),
        );
      },
      () => {
        setPublishedCourses([]);
      },
    );

    return unsubscribe;
  }, [user]);

  // The showcase is an ordered VIEW over the teacher's published courses:
  // saved order first (dropping courses no longer published), then any newly
  // published course appended in its natural order.
  const orderedCourses = useMemo(() => {
    const byId = new Map(publishedCourses.map((course) => [course.id, course]));
    const seen = new Set<string>();
    const ordered: TeacherCourse[] = [];

    for (const id of orderedCourseIds) {
      const course = byId.get(id);
      if (course && !seen.has(id)) {
        ordered.push(course);
        seen.add(id);
      }
    }

    for (const course of publishedCourses) {
      if (!seen.has(course.id)) {
        ordered.push(course);
        seen.add(course.id);
      }
    }

    return ordered;
  }, [publishedCourses, orderedCourseIds]);

  function reorder(index: number, direction: -1 | 1) {
    const ids = orderedCourses.map((course) => course.id);
    setOrderedCourseIds(moveItem(ids, index, direction));
  }

  async function handleStorefrontImageChange(
    kind: StorefrontImageKind,
    file: File | null,
  ) {
    if (!user || !file) {
      return;
    }

    if (!isAllowedAvatarFile(file)) {
      setImageError(kind, `Use a ${storefrontImageRequirementLabel} image.`);
      return;
    }

    setImageError(kind, "");
    setSuccess("");
    setUploadProgress((current) => {
      const next = { ...current };
      delete next[kind];
      return next;
    });
    setUploadingImages((current) => new Set(current).add(kind));

    try {
      const uploadedUrl = await uploadUserStorefrontImage(
        user.uid,
        kind,
        file,
        (progress) =>
          setUploadProgress((current) => ({ ...current, [kind]: progress })),
      );

      if (kind === "logo") {
        setLogoUrl(uploadedUrl);
      } else {
        setHeroImageUrl(uploadedUrl);
      }
      setPendingImageRemovals((current) => {
        const next = new Set(current);
        next.delete(kind);
        return next;
      });
      setSuccess(`${kind === "logo" ? "Logo" : "Hero image"} uploaded. Save the storefront to publish it.`);
    } catch (uploadError) {
      console.error("Storefront image upload failed", { uid: user.uid, kind }, uploadError);
      setImageError(
        kind,
        uploadError instanceof Error && uploadError.message
          ? uploadError.message
          : "We could not upload this image. Please try again.",
      );
    } finally {
      setUploadingImages((current) => {
        const next = new Set(current);
        next.delete(kind);
        return next;
      });
      setUploadProgress((current) => {
        const next = { ...current };
        delete next[kind];
        return next;
      });
    }
  }

  function handleStorefrontImageRemove(kind: StorefrontImageKind) {
    if (kind === "logo") {
      setLogoUrl("");
    } else {
      setHeroImageUrl("");
    }
    setPendingImageRemovals((current) => new Set(current).add(kind));
    setImageError(kind, "");
    setSuccess("Save the storefront to publish this removal.");
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!user) {
      setError("Sign in again to update your storefront.");
      return;
    }

    const trimmedAccent = accentColor.trim();
    const trimmedLogo = logoUrl.trim();
    const trimmedHero = heroImageUrl.trim();
    const trimmedTagline = tagline.trim();

    const validationError =
      (trimmedAccent && !isStorefrontHexColor(trimmedAccent)
        ? "Accent color must be a 6-digit hex like #183a5e."
        : "") ||
      (trimmedTagline.length > maxStorefrontTaglineLength
        ? `Tagline must be ${maxStorefrontTaglineLength} characters or fewer.`
        : "");

    if (validationError) {
      setError(validationError);
      return;
    }

    const ids = orderedCourses.map((course) => course.id);
    const storefront: StorefrontConfig = {
      branding: {
        accentColor: trimmedAccent || null,
        logoUrl: trimmedLogo || null,
        heroImageUrl: trimmedHero || null,
        themePreset,
      },
      showcase: {
        tagline: trimmedTagline || null,
        orderedCourseIds: ids,
        featuredCourseId:
          featuredCourseId && ids.includes(featuredCourseId)
            ? featuredCourseId
            : null,
      },
    };

    setError("");
    setSuccess("");
    setIsSaving(true);

    try {
      await updateUserStorefront(user.uid, storefront);
      const removals = [...pendingImageRemovals];
      const results = await Promise.allSettled(
        removals.map((kind) => removeUserStorefrontImage(user.uid, kind)),
      );
      const removedKinds = removals.filter(
        (_, index) => results[index]?.status === "fulfilled",
      );
      const cleanupFailed = results.some(
        (result) => result.status === "rejected",
      );

      if (removedKinds.length > 0) {
        setPendingImageRemovals((current) => {
          const next = new Set(current);
          removedKinds.forEach((kind) => next.delete(kind));
          return next;
        });
      }

      setSuccess("Storefront saved.");
      if (cleanupFailed) {
        setError(
          "The storefront was saved, but an old image could not be removed. Save again to retry cleanup.",
        );
      }
    } catch {
      setError(
        "We could not save your storefront. Try again, and contact support if it keeps failing.",
      );
    } finally {
      setIsSaving(false);
    }
  }

  if (isLoading) {
    return (
      <section className="settings-section-card">
        <p className="text-sm text-[var(--color-ink-soft)]">
          Loading storefront settings...
        </p>
      </section>
    );
  }

  const previewAccent =
    accentColor.trim() && isStorefrontHexColor(accentColor.trim())
      ? accentColor.trim()
      : defaultAccentColor;

  return (
    <section className="settings-section-card">
      <p className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--color-accent-fg)]">
        Teacher Studio
      </p>
      <h2 className="display-title mt-3 text-3xl text-[var(--color-primary)]">
        Storefront branding
      </h2>
      <p className="mt-3 max-w-2xl text-sm leading-7 text-[var(--color-ink-soft)]">
        Brand your public instructor page &mdash; logo, hero image, accent color,
        and the order your courses appear in. Saved here now; your public
        storefront goes live in a later step.
      </p>

      {/* Live brand preview — how your storefront header reads at a glance. */}
      <div className="mt-6 overflow-hidden rounded-[16px] border border-[var(--color-line)] shadow-[var(--shadow-soft)]">
        <div className="relative flex min-h-32 items-center gap-4 overflow-hidden bg-[var(--color-primary)] px-5 py-6 sm:px-7">
          {heroImageUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={heroImageUrl} alt="" className="absolute inset-0 h-full w-full object-cover" />
          ) : null}
          <span className="absolute inset-0 bg-[rgba(10,24,43,0.66)]" aria-hidden="true" />
          <span className="relative grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-[8px] bg-white/10 text-xl font-bold text-white ring-1 ring-white/20">
            {logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={logoUrl}
                alt="Storefront logo preview"
                className="h-full w-full object-contain p-1"
              />
            ) : (
              (displayName.trim()[0] ?? "S").toUpperCase()
            )}
          </span>
          <span className="relative min-w-0">
            <span className="block truncate text-base font-bold text-white">
              {displayName.trim() || "Your instructor page"}
            </span>
            <span className="mt-1 block max-w-md truncate text-sm text-white/70">
              {tagline.trim() || "One line that sums up what you teach."}
            </span>
          </span>
        </div>
        <div className="h-1.5" style={{ background: previewAccent }} />
      </div>

      <form className="mt-6 grid gap-5" onSubmit={handleSubmit}>
        <div className="grid gap-4 rounded-[14px] border border-[var(--color-line)] bg-[var(--color-surface-soft)] p-4">
          <p className="text-sm font-semibold text-[var(--color-ink)]">
            Brand
          </p>

          <label className="grid gap-2 text-sm font-semibold text-[var(--color-ink)]">
            Accent color
            <div className="flex items-center gap-3">
              <input
                type="color"
                value={previewAccent}
                onChange={(event) => setAccentColor(event.target.value)}
                aria-label="Accent color picker"
                className="h-11 w-14 shrink-0 cursor-pointer rounded-[10px] border border-[var(--color-line)] bg-white p-1"
              />
              <input
                value={accentColor}
                onChange={(event) => setAccentColor(event.target.value)}
                placeholder="#183a5e"
                spellCheck={false}
                className="min-w-0 flex-1 rounded-[10px] border border-[var(--color-line)] bg-white px-4 py-3 text-sm font-normal outline-none focus:border-[var(--color-primary-light)]"
              />
            </div>
            <span className="text-xs font-normal text-[var(--color-ink-soft)]">
              6-digit hex. Leave blank to use the platform default.
            </span>
          </label>

          <StorefrontImageUpload
            kind="logo"
            label="Storefront logo"
            description="Use a square image with a transparent or simple background. On paid plans it is also printed on the certificates you issue."
            imageUrl={logoUrl}
            error={imageErrors.logo ?? ""}
            isUploading={uploadingImages.has("logo")}
            progress={uploadProgress.logo ?? null}
            onChange={(file) => void handleStorefrontImageChange("logo", file)}
            onRemove={() => handleStorefrontImageRemove("logo")}
          />

          <StorefrontImageUpload
            kind="hero"
            label="Storefront cover"
            description="Use a wide image that keeps its subject clear on desktop and mobile."
            imageUrl={heroImageUrl}
            error={imageErrors.hero ?? ""}
            isUploading={uploadingImages.has("hero")}
            progress={uploadProgress.hero ?? null}
            onChange={(file) => void handleStorefrontImageChange("hero", file)}
            onRemove={() => handleStorefrontImageRemove("hero")}
          />

          <label className="grid gap-2 text-sm font-semibold text-[var(--color-ink)]">
            Theme preset
            <select
              value={themePreset}
              onChange={(event) =>
                setThemePreset(event.target.value as StorefrontThemePreset)
              }
              className="rounded-[10px] border border-[var(--color-line)] bg-white px-4 py-3 text-sm font-normal outline-none focus:border-[var(--color-primary-light)]"
            >
              {storefrontThemePresets.map((preset) => (
                <option key={preset} value={preset}>
                  {themePresetLabels[preset]}
                </option>
              ))}
            </select>
          </label>

          <label className="grid gap-2 text-sm font-semibold text-[var(--color-ink)]">
            Tagline
            <textarea
              value={tagline}
              onChange={(event) => setTagline(event.target.value)}
              rows={2}
              maxLength={maxStorefrontTaglineLength}
              placeholder="One line that sums up what you teach."
              className="resize-none rounded-[10px] border border-[var(--color-line)] bg-white px-4 py-3 text-sm font-normal outline-none focus:border-[var(--color-primary-light)]"
            />
            <span className="text-xs font-normal text-[var(--color-ink-soft)]">
              {tagline.trim().length}/{maxStorefrontTaglineLength} characters
            </span>
          </label>
        </div>

        <div className="grid gap-3 rounded-[14px] border border-[var(--color-line)] bg-[var(--color-surface-soft)] p-4">
          <div className="flex flex-wrap items-baseline justify-between gap-2">
            <p className="text-sm font-semibold text-[var(--color-ink)]">
              Course showcase order
            </p>
            <span className="text-xs font-normal text-[var(--color-ink-soft)]">
              Published courses only
            </span>
          </div>

          {orderedCourses.length === 0 ? (
            <p className="text-xs leading-5 text-[var(--color-ink-soft)]">
              You have no published courses yet. Once a course is published it
              shows up here for ordering.
            </p>
          ) : (
            <ol className="grid gap-2">
              {orderedCourses.map((course, index) => {
                const isFeatured = featuredCourseId === course.id;
                return (
                  <li
                    key={course.id}
                    className="flex flex-wrap items-center gap-3 rounded-[10px] border border-[var(--color-line)] bg-white px-3 py-2.5"
                  >
                    <span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[var(--color-surface-soft)] text-xs font-semibold text-[var(--color-ink-soft)]">
                      {index + 1}
                    </span>
                    <span className="min-w-0 flex-1 truncate text-sm font-semibold text-[var(--color-ink)]">
                      {course.title}
                    </span>
                    <button
                      type="button"
                      onClick={() =>
                        setFeaturedCourseId(isFeatured ? null : course.id)
                      }
                      aria-pressed={isFeatured}
                      className={`shrink-0 rounded-[8px] border px-2.5 py-1.5 text-xs font-semibold ${
                        isFeatured
                          ? "border-[var(--color-primary)] bg-[rgba(24,58,94,0.08)] text-[var(--color-primary)]"
                          : "border-[var(--color-line)] text-[var(--color-ink-soft)]"
                      }`}
                    >
                      {isFeatured ? "Featured" : "Feature"}
                    </button>
                    <div className="flex shrink-0 gap-1">
                      <button
                        type="button"
                        onClick={() => reorder(index, -1)}
                        disabled={index === 0}
                        aria-label={`Move ${course.title} up`}
                        className="rounded-[8px] border border-[var(--color-line)] px-2.5 py-1.5 text-xs font-semibold text-[var(--color-ink-soft)] disabled:opacity-40"
                      >
                        ↑
                      </button>
                      <button
                        type="button"
                        onClick={() => reorder(index, 1)}
                        disabled={index === orderedCourses.length - 1}
                        aria-label={`Move ${course.title} down`}
                        className="rounded-[8px] border border-[var(--color-line)] px-2.5 py-1.5 text-xs font-semibold text-[var(--color-ink-soft)] disabled:opacity-40"
                      >
                        ↓
                      </button>
                    </div>
                  </li>
                );
              })}
            </ol>
          )}
        </div>

        {error ? (
          <p className="rounded-[10px] border border-[rgba(178,34,52,0.2)] bg-[rgba(178,34,52,0.06)] px-4 py-3 text-sm font-semibold text-[var(--color-danger-fg)]">
            {error}
          </p>
        ) : null}

        {success ? <p className="info-notice">{success}</p> : null}

        <button
          type="submit"
          disabled={isSaving || uploadingImages.size > 0}
          className="button-solid justify-self-start px-4 py-2.5 text-sm disabled:opacity-60"
        >
          {isSaving ? "Saving..." : "Save storefront"}
        </button>
      </form>
    </section>
  );
}
